// ============================================================================
// MAAD.md Generator
// Generates the LLM instruction file for a MAAD project.
// Updated on init and reindex to reflect current registry and schemas.
// ============================================================================

import type { Registry, SchemaStore, FieldDefinition, BackendStats } from './types.js';

export interface MaadMdContext {
  projectRoot: string;
  enginePath: string;
  registry: Registry;
  schemaStore: SchemaStore;
  stats: BackendStats | null;
}

export function generateMaadMd(ctx: MaadMdContext): string {
  const cmd = buildCmdPrefix(ctx.enginePath, ctx.projectRoot);
  const sections: string[] = [];

  sections.push(generateHeader(cmd));
  sections.push(generateQuickStart(cmd, ctx));
  sections.push(generateFullCommandRef(cmd));
  sections.push(generateTypes(ctx));
  sections.push(generatePrimitives());
  sections.push(generateRules());
  sections.push(generateFeedback());

  return sections.join('\n\n---\n\n') + '\n';
}

function buildCmdPrefix(enginePath: string, projectRoot: string): string {
  return `node ${enginePath} --project ${projectRoot}`;
}

// ---- Sections -------------------------------------------------------------

function generateHeader(cmd: string): string {
  return `# MAAD.md — LLM Interface

> Auto-generated by the MAAD engine. Regenerated on \`reindex\`. Do not edit.
>
> **This is a test/evaluation project.** If you find issues or have improvement ideas,
> create a feedback file: \`feedback-YYYY-MM-DD-<model>.md\` (e.g. \`feedback-2026-04-07-gpt-5.md\`).

## What is this?

A **MAAD project** — a markdown-native database. Markdown files are the records. A queryable index gives you structured access without reading full files.

## How to run commands

\`\`\`
${cmd} <command> [args]
\`\`\`

All output is JSON unless noted.`;
}

function generateQuickStart(cmd: string, ctx: MaadMdContext): string {
  const totalDocs = ctx.stats?.totalDocuments ?? 0;
  const typeList = [...ctx.registry.types.values()].map(t => `\`${t.name as string}\``).join(', ');
  const typeCount = ctx.registry.types.size;

  // Build a realistic first-run sequence using actual data from this project
  const firstType = [...ctx.registry.types.values()][0];
  const firstTypeStr = firstType ? (firstType.name as string) : 'type';

  return `## Quick Start (do this first)

This project has **${totalDocs} documents** across **${typeCount} types**: ${typeList}.

**Step 1 — See what exists:**
\`\`\`
${cmd} describe
\`\`\`

**Step 2 — Find records:**
\`\`\`
${cmd} query ${firstTypeStr}
\`\`\`

**Step 3 — Read a record (frontmatter only, minimal tokens):**
\`\`\`
${cmd} get <doc_id> hot
\`\`\`

**Step 4 — Read a specific section:**
\`\`\`
${cmd} get <doc_id> warm <block_id>
\`\`\`

**Step 5 — See what's connected:**
\`\`\`
${cmd} related <doc_id> both
\`\`\`

**Step 6 — Search across all documents:**
\`\`\`
${cmd} search entity --subtype person
\`\`\`

You now know the project. Most questions can be answered from steps 2-5 without a full file read.`;
}

function generateFullCommandRef(cmd: string): string {
  return `## All Commands

### Read
| Command | What it does |
|---------|-------------|
| \`describe\` | Project overview: types, doc counts, primitives |
| \`get <doc_id> hot\` | Frontmatter only (cheapest read) |
| \`get <doc_id> warm <block>\` | Frontmatter + one section |
| \`get <doc_id> cold\` | Full document (expensive — use sparingly) |
| \`query <type>\` | All documents of a type |
| \`query <type> --filter field=value\` | Filtered by indexed field |
| \`search <primitive>\` | Cross-document object search |
| \`search <primitive> --subtype <s>\` | Filter by subtype (e.g. person, attorney) |
| \`search <primitive> --contains <text>\` | Substring match on values |
| \`related <doc_id> both\` | All connected documents (outgoing + incoming) |
| \`related <doc_id> outgoing\` | Documents this one references |
| \`related <doc_id> incoming\` | Documents that reference this one |
| \`inspect <doc_id>\` | Full engine internals: blocks, objects, relationships, validation |

### Write
| Command | What it does |
|---------|-------------|
| \`create <type> --field k=v [--field k=v ...] [--body "text"] [--id custom-id]\` | Create a new record |
| \`update <doc_id> --field k=v [--field k=v ...]\` | Update frontmatter fields |
| \`update <doc_id> --append "text"\` | Append to document body |
| \`update <doc_id> --body "text"\` | Replace document body |

### Maintain
| Command | What it does |
|---------|-------------|
| \`validate\` | Validate all documents against schemas |
| \`validate <doc_id>\` | Validate one document |
| \`reindex --force\` | Rebuild the full index from markdown |
| \`parse <file.md>\` | Parse one file, show structure |

### Audit (requires git)
| Command | What it does |
|---------|-------------|
| \`history <doc_id>\` | Change history for a document |
| \`audit\` | Project-wide activity |
| \`audit --since <date>\` | Activity since a date |

### Field syntax for create/update
- String: \`--field name=Acme Corp\`
- Enum: \`--field status=open\`
- Ref: \`--field client=cli-acme\`
- Array: \`--field tags=[enterprise,priority]\`
- Date: \`--field opened_at=2026-04-07\``;
}

function generateTypes(ctx: MaadMdContext): string {
  if (ctx.registry.types.size === 0) {
    return `## Types\n\nNo types registered yet.`;
  }

  const lines: string[] = ['## Registered Types\n'];

  for (const [, regType] of ctx.registry.types) {
    const count = ctx.stats?.documentCountByType[regType.name as string] ?? 0;
    const schema = ctx.schemaStore.getSchemaForType(regType.name);

    lines.push(`### \`${regType.name as string}\` — ${count} docs | prefix: \`${regType.idPrefix}\` | schema: \`${regType.schemaRef as string}\``);

    if (schema) {
      const requiredStr = schema.required.filter(r => r !== 'doc_id').join(', ');
      if (requiredStr) lines.push(`**Required:** ${requiredStr}`);

      if (schema.fields.size > 0) {
        lines.push('');
        lines.push('| Field | Type | Details |');
        lines.push('|-------|------|---------|');
        for (const [name, field] of schema.fields) {
          lines.push(`| \`${name}\` | ${formatFieldType(field)} | ${formatFieldDetails(field)} |`);
        }
      }
    }

    lines.push('');
  }

  if (Object.keys(ctx.registry.extraction.subtypes).length > 0) {
    lines.push('### Custom Extraction Subtypes\n');
    lines.push('| Subtype | Primitive |');
    lines.push('|---------|-----------|');
    for (const [subtype, primitive] of Object.entries(ctx.registry.extraction.subtypes)) {
      lines.push(`| \`${subtype}\` | \`${primitive}\` |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function formatFieldType(field: FieldDefinition): string {
  let t = field.type as string;
  if (field.type === 'ref' && field.target) t = `ref -> ${field.target as string}`;
  if (field.type === 'list' && field.itemType) {
    t = `list of ${field.itemType}`;
    if (field.target) t += ` -> ${field.target as string}`;
  }
  if (field.type === 'enum' && field.values) t = `enum`;
  return t;
}

function formatFieldDetails(field: FieldDefinition): string {
  const parts: string[] = [];
  if (field.index) parts.push('indexed');
  if (field.role) parts.push(`role: ${field.role}`);
  if (field.type === 'enum' && field.values) parts.push(field.values.join(', '));
  if (field.format) parts.push(`format: ${field.format}`);
  return parts.join(' | ') || '—';
}

function generatePrimitives(): string {
  return `## Extraction Primitives

Inline annotations in markdown body use \`[[type:value|label]]\` syntax. The engine extracts and indexes them.

| Primitive | Captures | Search example |
|-----------|----------|---------------|
| \`entity\` | person, org, team, product | \`search entity --subtype person\` |
| \`date\` | date, datetime | \`search date --contains 2026\` |
| \`duration\` | time span (3 hours, 2 weeks) | \`search duration\` |
| \`amount\` | currency (100.00 USD, $500) | \`search amount\` |
| \`measure\` | value + unit (500mg, 6 feet) | \`search measure\` |
| \`quantity\` | bare count (42, 1800) | \`search quantity\` |
| \`percentage\` | ratio (15%, 0.85) | \`search percentage\` |
| \`location\` | place, address | \`search location\` |
| \`identifier\` | case number, invoice, code | \`search identifier\` |
| \`contact\` | email, phone, URL | \`search contact\` |
| \`media\` | image, video, audio, document | \`search media\` |`;
}

function generateRules(): string {
  return `## Rules

1. **Run \`describe\` first** in every new session
2. **Use \`hot\` reads by default** — escalate to \`warm\` then \`cold\` only when needed
3. **Use the CLI for writes** — never edit markdown files directly
4. **Use \`search\` for cross-document queries** — don't open files to find people/dates/amounts
5. **Use \`related\` for graph traversal** — don't manually search for connected docs
6. **Cite \`doc_id\` and \`block_id\`** in answers for traceability
7. **\`reindex --force\`** recovers from any stale state`;
}

function generateFeedback(): string {
  return `## Feedback

This is a test/evaluation project. If you encounter issues, friction, or have improvement suggestions:

1. Create a file in the project root: \`feedback-YYYY-MM-DD-<model>.md\`
   - Example: \`feedback-2026-04-07-gpt-5.md\`
   - Example: \`feedback-2026-04-08-claude-opus.md\`
2. Structure your feedback with:
   - **Observations** — what happened, what you expected
   - **Suggestions** — how to improve it
   - **Context** — what you were trying to do when the issue occurred
3. Do not modify existing feedback files from other models`;
}

export function generateStubMaadMd(enginePath: string, projectRoot: string): string {
  const cmd = buildCmdPrefix(enginePath, projectRoot);
  return `# MAAD.md — LLM Interface

> Auto-generated by the MAAD engine.
> Run \`reindex\` after adding types and schemas to update this file.
>
> **This is a test/evaluation project.** If you find issues, create a feedback file:
> \`feedback-YYYY-MM-DD-<model>.md\`

This is a **MAAD project** — a markdown-native database.

## Getting Started

1. Define types in \`_registry/object_types.yaml\`
2. Create schemas in \`_schema/\`
3. Add markdown records
4. Run: \`${cmd} reindex --force\`

This file will be regenerated with full type/command reference after the first reindex.
`;
}
