// ============================================================================
// SCHEMA.md Generator
// Generates the project data index file for LLM consumption.
// Updated on reindex to reflect current registry, schemas, and doc counts.
// This is the "what's in this project" file — types, fields, counts, subtypes.
// ============================================================================

import type { Registry, SchemaStore, FieldDefinition, BackendStats } from './types.js';

export interface SchemaMdContext {
  registry: Registry;
  schemaStore: SchemaStore;
  stats: BackendStats | null;
}

export function generateSchemaMd(ctx: SchemaMdContext): string {
  const sections: string[] = [];

  sections.push(generateHeader(ctx));
  sections.push(generateTypeSummary(ctx));
  sections.push(generateTypeDetails(ctx));

  if (Object.keys(ctx.registry.extraction.subtypes).length > 0) {
    sections.push(generateCustomSubtypes(ctx));
  }

  return sections.join('\n\n') + '\n';
}

function generateHeader(ctx: SchemaMdContext): string {
  const totalDocs = ctx.stats?.totalDocuments ?? 0;
  const typeCount = ctx.registry.types.size;
  const typeList = [...ctx.registry.types.values()].map(t => `\`${t.name as string}\``).join(', ');

  return `# SCHEMA.md — Project Data Index

> Auto-generated by the MAAD engine on \`reindex\`. Do not edit.

**${totalDocs} documents** across **${typeCount} types**: ${typeList}`;
}

function generateTypeSummary(ctx: SchemaMdContext): string {
  const lines: string[] = ['## Overview\n'];
  lines.push('| Type | Docs | Prefix | Required Fields |');
  lines.push('|------|------|--------|----------------|');

  for (const [, regType] of ctx.registry.types) {
    const count = ctx.stats?.documentCountByType[regType.name as string] ?? 0;
    const schema = ctx.schemaStore.getSchemaForType(regType.name);
    const required = schema
      ? schema.required.filter(r => r !== 'doc_id').join(', ')
      : '—';

    lines.push(`| \`${regType.name as string}\` | ${count} | \`${regType.idPrefix}\` | ${required} |`);
  }

  return lines.join('\n');
}

function generateTypeDetails(ctx: SchemaMdContext): string {
  const lines: string[] = ['## Types\n'];

  for (const [, regType] of ctx.registry.types) {
    const count = ctx.stats?.documentCountByType[regType.name as string] ?? 0;
    const schema = ctx.schemaStore.getSchemaForType(regType.name);

    lines.push(`### \`${regType.name as string}\` — ${count} docs`);
    lines.push(`prefix: \`${regType.idPrefix}\` | schema: \`${regType.schemaRef as string}\` | path: \`${regType.path}\``);

    if (schema) {
      if (schema.fields.size > 0) {
        lines.push('');
        lines.push('| Field | Type | Indexed | Details |');
        lines.push('|-------|------|---------|---------|');
        for (const [name, field] of schema.fields) {
          const required = schema.required.includes(name) ? '**yes**' : 'no';
          lines.push(`| \`${name}\` | ${formatType(field)} | ${field.index ? 'yes' : 'no'} | ${formatDetails(field, required)} |`);
        }
      }
    }

    lines.push('');
  }

  return lines.join('\n');
}

function generateCustomSubtypes(ctx: SchemaMdContext): string {
  const lines: string[] = ['## Custom Extraction Subtypes\n'];
  lines.push('These subtypes are project-specific and map to engine primitives.\n');
  lines.push('| Subtype | Primitive | Use in annotations |');
  lines.push('|---------|-----------|-------------------|');

  for (const [subtype, primitive] of Object.entries(ctx.registry.extraction.subtypes)) {
    lines.push(`| \`${subtype}\` | \`${primitive}\` | \`[[${subtype}:value|label]]\` |`);
  }

  return lines.join('\n');
}

function formatType(field: FieldDefinition): string {
  let t = field.type as string;
  if (field.type === 'ref' && field.target) t = `ref -> \`${field.target as string}\``;
  if (field.type === 'list' && field.itemType) {
    t = `list of ${field.itemType}`;
    if (field.target) t += ` -> \`${field.target as string}\``;
  }
  if (field.type === 'enum') t = 'enum';
  return t;
}

function formatDetails(field: FieldDefinition, required: string): string {
  const parts: string[] = [];
  if (required === '**yes**') parts.push('required');
  if (field.role) parts.push(`role: ${field.role}`);
  if (field.type === 'enum' && field.values) parts.push(field.values.join(', '));
  if (field.format) parts.push(field.format);
  return parts.join(' | ') || '—';
}
