// ============================================================================
// Auth types — 0.7.0 Scoped Auth & Identity (dec-maadb-069 + dec-maadb-071)
//
// Token registry lives at <instance-root>/_auth/tokens.yaml. Plaintext tokens
// use format `maad_pat_<32hex>` — 128-bit random + shell-safe + prefix
// recognizable in logs and leaked-credential scanners. Plaintext is returned
// ONCE at issue/rotate; SHA-256 hash is what persists.
//
// Records are IMMUTABLE except `revokedAt`. Three operations: issue, rotate,
// revoke. Any capability change (role / identity / projects) requires revoke
// + reissue. Rationale in dec-maadb-069 lock #8.
// ============================================================================

import type { Role } from '../mcp/roles.js';

/**
 * Readable token identifier for CLI + audit trails. Generated at issue time.
 * Format: `tok-<12hex>`. Distinct from the hash (lookup key) and plaintext
 * (bearer presented by clients).
 */
export type TokenId = string & { readonly __brand: 'TokenId' };

/** SHA-256 hex digest of the plaintext bearer. Lookup key; persisted. */
export type TokenHash = string & { readonly __brand: 'TokenHash' };

export function tokenId(s: string): TokenId { return s as TokenId; }
export function tokenHash(s: string): TokenHash { return s as TokenHash; }

/**
 * Per-token project access entry. Wildcard `*` matches every project in the
 * instance at the token's global role. A named entry may optionally downgrade
 * the role for that specific project via an explicit `role` field — the
 * per-project cap can only REDUCE, never exceed the global role (enforced at
 * resolve time, not load time).
 */
export interface ProjectCap {
  name: string;       // project name or '*'
  role?: Role;        // optional per-project role override (never exceeds global)
}

/**
 * Full token record as persisted in tokens.yaml. Plaintext is NOT stored
 * anywhere — only the SHA-256 hash of plaintext. revokedAt is the only
 * field that can transition on an existing record; everything else is
 * immutable (per dec-maadb-069 lock #8).
 */
export interface TokenRecord {
  id: TokenId;
  name?: string;
  hash: TokenHash;
  role: Role;
  projects: ProjectCap[];
  agentId?: string;      // ref -> agent (identity attribution)
  userId?: string;       // ref -> user (when token represents a human)
  expiresAt?: string;    // ISO 8601
  createdAt: string;     // ISO 8601
  revokedAt?: string;    // ISO 8601 — presence means revoked
}

/**
 * Payload accepted by TokenStore.issue. Everything a caller supplies at
 * token creation. `id` and `hash` are generated by the store; `createdAt`
 * is stamped at issue time.
 */
export interface IssueSpec {
  name?: string;
  role: Role;
  projects: ProjectCap[];
  agentId?: string;
  userId?: string;
  expiresAt?: string;
}

/**
 * Result of a successful issue or rotate. Plaintext is returned ONCE — the
 * caller is responsible for delivering it to the end user and it's never
 * recoverable from the registry afterward.
 */
export interface IssuedToken {
  record: TokenRecord;
  plaintext: string;
}

/**
 * Shape of tokens.yaml on disk. Top-level `name` is an optional human label
 * for the registry file itself (distinct from per-token `name`).
 */
export interface TokensFileShape {
  name?: string;
  tokens: TokenRecord[];
}
